# Generated by Django 4.1 on 2023-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_alter_reserva_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
