# Generated by Django 4.1 on 2023-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_reserva_laboratorio_alter_alumno_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='herramienta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
