# Generated by Django 4.1 on 2023-06-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0005_reserva_herramienta_reserva_hora_alter_reserva_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
