# Generated by Django 4.1 on 2023-06-30 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0008_remove_reserva_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
