# Generated by Django 4.1 on 2023-06-30 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0009_reserva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
